In [1]:
import os
import numpy as np
import csv
import cvxopt
from numpy.linalg import inv

In [2]:
U=3
N=3

In [3]:
with open('data_pilot_contamination.csv') as csv_file:
    csv_reader = csv.reader(csv_file)
    data = list(csv_reader)

In [4]:
data=np.array(data)

In [5]:
data=np.delete(data,-1,1)   # delete last column of data

In [6]:
data

array([['0.354688+2.82253e-08i', '1.39008-1.19565i', '-0.515333+2.26203i'],
       ['1.39008+1.19565i', '9.47851-1.88798e-08i', '-9.64496+7.12809i'],
       ['-0.515333-2.26203i', '-9.64496-7.12809i', '15.1749-1.22368e-08i'],
       ['2.83042-2.63932e-10i', '-4.0405+1.07721i', '6.04181-6.25605i'],
       ['-4.0405-1.07721i', '6.1779+5.47623e-09i', '-11.0058+6.63127i'],
       ['6.04181+6.25605i', '-11.0058-6.63127i', '26.7246+5.79387e-09i'],
       ['11.8811-4.75101e-10i', '0.249695-15.5678i', '-24.3848+5.39302i'],
       ['0.249695+15.5678i', '20.4038+1.0657e-08i', '-7.57897-31.8382i'],
       ['-24.3848-5.39302i', '-7.57897+31.8382i', '52.4957+6.05619e-09i']], 
      dtype='<U21')

In [7]:
for i in range(N*U):
    for j in range(N):
        data[i][j] = data[i][j].replace('i', 'j')
        #data[i][j] = data[i][j].replace(" ", "")
        #data[i][j]=complex(data[i][j])

In [8]:
data

array([['0.354688+2.82253e-08j', '1.39008-1.19565j', '-0.515333+2.26203j'],
       ['1.39008+1.19565j', '9.47851-1.88798e-08j', '-9.64496+7.12809j'],
       ['-0.515333-2.26203j', '-9.64496-7.12809j', '15.1749-1.22368e-08j'],
       ['2.83042-2.63932e-10j', '-4.0405+1.07721j', '6.04181-6.25605j'],
       ['-4.0405-1.07721j', '6.1779+5.47623e-09j', '-11.0058+6.63127j'],
       ['6.04181+6.25605j', '-11.0058-6.63127j', '26.7246+5.79387e-09j'],
       ['11.8811-4.75101e-10j', '0.249695-15.5678j', '-24.3848+5.39302j'],
       ['0.249695+15.5678j', '20.4038+1.0657e-08j', '-7.57897-31.8382j'],
       ['-24.3848-5.39302j', '-7.57897+31.8382j', '52.4957+6.05619e-09j']], 
      dtype='<U21')

In [9]:
data=data.astype(complex)

In [10]:
data

array([[  0.354688 +2.82253000e-08j,   1.390080 -1.19565000e+00j,
         -0.515333 +2.26203000e+00j],
       [  1.390080 +1.19565000e+00j,   9.478510 -1.88798000e-08j,
         -9.644960 +7.12809000e+00j],
       [ -0.515333 -2.26203000e+00j,  -9.644960 -7.12809000e+00j,
         15.174900 -1.22368000e-08j],
       [  2.830420 -2.63932000e-10j,  -4.040500 +1.07721000e+00j,
          6.041810 -6.25605000e+00j],
       [ -4.040500 -1.07721000e+00j,   6.177900 +5.47623000e-09j,
        -11.005800 +6.63127000e+00j],
       [  6.041810 +6.25605000e+00j, -11.005800 -6.63127000e+00j,
         26.724600 +5.79387000e-09j],
       [ 11.881100 -4.75101000e-10j,   0.249695 -1.55678000e+01j,
        -24.384800 +5.39302000e+00j],
       [  0.249695 +1.55678000e+01j,  20.403800 +1.06570000e-08j,
         -7.578970 -3.18382000e+01j],
       [-24.384800 -5.39302000e+00j,  -7.578970 +3.18382000e+01j,
         52.495700 +6.05619000e-09j]])

In [11]:
H_pre=[[],[],[]]
l=0
u=N
for i in range(0,U):
    H_pre[i]=data[l:u]
    l=l+N
    u=l+N

In [12]:
H_pre_trans=[[],[],[]]
for i in range(0,U):
    H_pre_trans[i]=np.transpose(H_pre[i])

In [54]:
H=[[],[],[]]
for i in range(U):
    H[i]=H_pre[i]+H_pre_trans[i]

In [13]:
# processing of h_hat_vector

In [14]:
h=[[],[],[]]
with open('h_hat_data.csv') as h_file:
    h_reader = csv.reader(h_file)
    h_hat = list(h_reader)

In [15]:
h_hat=np.array(h_hat)

In [16]:
h_hat=np.delete(h_hat,-1,1)   # delete last column of h_hat
h_hat

array([['-9.10403+9.99542i', '-2.19513+2.02451i', '-0.117999+0.227934i'],
       ['-10.2877+5.20034i', '-3.71424-10.4307i', '-0.664235-6.28324i'],
       ['2.44262-1.27425i', '-15.388+2.60369i', '0.3515-6.33737i']], 
      dtype='<U19')

In [17]:
for i in range(U):
    for j in range(N):
        h_hat[i][j] = h_hat[i][j].replace('i', 'j')

In [18]:
h_hat[1]

array(['-10.2877+5.20034j', '-3.71424-10.4307j', '-0.664235-6.28324j'], 
      dtype='<U19')

In [19]:
h_hat=h_hat.astype(complex)

In [20]:
h_hat

array([[ -9.104030 +9.99542j ,  -2.195130 +2.02451j ,  -0.117999 +0.227934j],
       [-10.287700 +5.20034j ,  -3.714240-10.4307j  ,  -0.664235 -6.28324j ],
       [  2.442620 -1.27425j , -15.388000 +2.60369j ,   0.351500 -6.33737j ]])

In [21]:
for i in range(0,U):
    h[i]=h_hat[i]

In [22]:
h

[array([-9.104030+9.99542j , -2.195130+2.02451j , -0.117999+0.227934j]),
 array([-10.287700 +5.20034j,  -3.714240-10.4307j ,  -0.664235 -6.28324j]),
 array([  2.44262-1.27425j, -15.38800+2.60369j,   0.35150-6.33737j])]

In [52]:
f_bu=[[],[],[]]
#lambda # lagrange parameter
for i in range(0,U):
    f_bu[i]=2*(2*lambda*np.eye(N) + H_pre[i] + np.transpose(H_pre[i]) )

SyntaxError: invalid syntax (<ipython-input-52-a1b5b8c2cddb>, line 4)

In [53]:
from cvxopt import matrix, solvers


In [58]:
H[0]

array([[  0.709376 +5.64506000e-08j,   2.780160 +0.00000000e+00j,
         -1.030666 +0.00000000e+00j],
       [  2.780160 +0.00000000e+00j,  18.957020 -3.77596000e-08j,
        -19.289920 +0.00000000e+00j],
       [ -1.030666 +0.00000000e+00j, -19.289920 +0.00000000e+00j,
         30.349800 -2.44736000e-08j]])

In [50]:
lambda

SyntaxError: invalid syntax (<ipython-input-50-8c8a4646591e>, line 1)

In [49]:
f_bu[0]

[]

In [40]:
lmda

0

In [25]:
a=np.transpose(H_pre[2])
a

array([[ 11.881100 -4.75101000e-10j,   0.249695 +1.55678000e+01j,
        -24.384800 -5.39302000e+00j],
       [  0.249695 -1.55678000e+01j,  20.403800 +1.06570000e-08j,
         -7.578970 +3.18382000e+01j],
       [-24.384800 +5.39302000e+00j,  -7.578970 -3.18382000e+01j,
         52.495700 +6.05619000e-09j]])

In [26]:
H_pre[2]

array([[ 11.881100 -4.75101000e-10j,   0.249695 -1.55678000e+01j,
        -24.384800 +5.39302000e+00j],
       [  0.249695 +1.55678000e+01j,  20.403800 +1.06570000e-08j,
         -7.578970 -3.18382000e+01j],
       [-24.384800 -5.39302000e+00j,  -7.578970 +3.18382000e+01j,
         52.495700 +6.05619000e-09j]])

In [27]:
a

array([[ 11.881100 -4.75101000e-10j,   0.249695 +1.55678000e+01j,
        -24.384800 -5.39302000e+00j],
       [  0.249695 -1.55678000e+01j,  20.403800 +1.06570000e-08j,
         -7.578970 +3.18382000e+01j],
       [-24.384800 +5.39302000e+00j,  -7.578970 -3.18382000e+01j,
         52.495700 +6.05619000e-09j]])

In [ ]:
a

In [ ]:
a=np.asmatrix(a)
a

In [ ]:
b=np.asmatrix(H_pre[2])
b

In [ ]:
c=a+b

In [ ]:
#code for the text file
# text_file = open("pilot_contamination_data.txt", "r")
# H_pre=[[],[],[]]
# H_pre_trans=[[],[],[]]
# h_hat=[[],[],[]]
# text_file.readline()
# text_file.readline()
# line_number=U-1
# for u in range(0,U):
#     for i in range(0,N):
#         #H_pre=text_file.read().split("\n")[line_number]
#         H_pre[u].insert(i,text_file.readline())
#         H_pre[u][-1] = H_pre[u][-1].strip()
#     text_file.readline()
#     H_pre[u]=np.array(H_pre[u])
# #text_file.readline()
# for u in range(0,U):
#     for i in range(0,N):
#         #H_pre=text_file.read().split("\n")[line_number]
#         H_pre_trans[u].insert(i,text_file.readline())
#         H_pre_trans[u][-1] = H_pre_trans[u][-1].strip()
#     text_file.readline()
# #text_file.readline()
# for u in range(3):
#     for i in range(1):
#         #H_pre=text_file.read().split("\n")[line_number]
#         h_hat[u].insert(i,text_file.readline())
#         h_hat[u][-1] = h_hat[u][-1].strip()
#     text_file.readline()
